name: build-unsafe
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        run: echo "VERSION=$(cat tailscale/VERSION.txt)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.unsafe
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ngc7331/derper:latest-unsafe, ngc7331/derper:${{ env.VERSION }}-unsafe
