name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - dockerfile-suffix: ""
            tag-suffix: ""
          - dockerfile-suffix: ".unsafe"
            tag-suffix: "-unsafe"

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        id: version
        run: echo "VERSION=$(cat tailscale/VERSION.txt)" >> $GITHUB_OUTPUT

      - name: Build
        uses: ngc7331/actions@docker-build
        with:
          name: derper
          version: ${{ steps.version.outputs.VERSION }}
          suffix: ${{ matrix.tag-suffix }}
          suffix_detailed: ${{ matrix.tag-suffix }}
          file: ./Dockerfile${{ matrix.dockerfile-suffix }}
          platforms: linux/amd64,linux/arm64,linux/riscv64
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
